AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CI Github App

Resources:
  Webhooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.webhooks
      Runtime: nodejs10.x
