AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CI Github App

Resources:
  Webhooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.webhooks
      Runtime: nodejs10.x
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "secretsmanager:GetResourcePolicy"
                - "secretsmanager:GetSecretValue"
                - "secretsmanager:DescribeSecret"
                - "secretsmanager:ListSecretVersionIds"
                - "secretsmanager:ListSecrets"
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ci-github-app/*"
      Timeout: 600
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: Any
