version: "2.1"
orbs:
  sam: circleci/aws-sam-serverless@3.1.0
jobs:
  test_my_api:
    docker:
      - image: "cimg/node:lts"
    steps:
      - run: echo "Run your API tests here"
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          context: aws-creds
          name: deploy
          s3-bucket: ci-github-app-sam
          stack-name: ci-github-app
          template: ./template.yaml
          capabilities: CAPABILITY_NAMED_IAM
